package xyz.ronella.trivial.handy;

import xyz.ronella.trivial.functional.NoOperation;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * A convenience class for creating a map as factory.
 *
 * @param <TYPE_OUTPUT> The type of the output that the factory will create.
 *
 * @author Ron Webb
 *
 * @since 2.2.0
 */
public class StringKeyedMapFactory<TYPE_OUTPUT> {

    private final Map<String, Supplier<TYPE_OUTPUT>> internalMap;
    private final Supplier<TYPE_OUTPUT> defaultLogic;

    /**
     * Creates an instance of StringKeyedMapFactory
     *
     * @param map An external map that will be used as storage of factory.
     * @param defaultLogic The default create logic if the key used was not in the map.
     * @param logics An arrays of create logic mapped to key.
     */
    @SafeVarargs
    public StringKeyedMapFactory(Map<String, Supplier<TYPE_OUTPUT>> map, Supplier<TYPE_OUTPUT> defaultLogic, Map.Entry<String, Supplier<TYPE_OUTPUT>> ... logics) {
        this.internalMap = Optional.ofNullable(map).orElse(new HashMap<>());
        this.defaultLogic = Optional.ofNullable(defaultLogic).orElse(NoOperation.supplier());
        Optional.ofNullable(logics).ifPresent(___logics -> {
            Arrays.asList(___logics).forEach(___logic -> {
                internalMap.put(___logic.getKey(), ___logic.getValue());
            });
        });
    }

    /**
     * Creates an instance of StringKeyedMapFactory
     *
     * @param defaultLogic The default create logic if the key used was not in the map.
     * @param logics An arrays of create logic mapped to key.
     */
    @SafeVarargs
    public StringKeyedMapFactory(Supplier<TYPE_OUTPUT> defaultLogic, Map.Entry<String, Supplier<TYPE_OUTPUT>> ... logics) {
        this(null, defaultLogic, logics);
    }

    /**
     * Creates an instance of StringKeyedMapFactory
     *
     * @param logics An arrays of create logic mapped to key.
     */
    @SafeVarargs
    public StringKeyedMapFactory(Map.Entry<String, Supplier<TYPE_OUTPUT>> ... logics) {
        this(null, logics);
    }

    /**
     * Executes the create logic of particular key.
     *
     * @param key The key of the create logic otherwise it will use the default create logic.
     *
     * @return The typed object generated by the create logic of the particular key.
     */
    public Optional<TYPE_OUTPUT> create(String key) {
        return Optional.ofNullable(internalMap.getOrDefault(key, defaultLogic).get());
    }

}
