name: build-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: corretto

      - name: Build with Gradle
        run: gradle build -PsnykToken="${{ secrets.SNYK_TOKEN }}" --stacktrace
