name: build-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build -PsnykToken="${{ secrets.SNYK_TOKEN }}"
