name: Dependency Submission

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master        

permissions:
  contents: write

jobs:
  dependency-submission:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: corretto

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4