name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build