name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    name: Build on Linux with snyk scan

    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

  build-windows:
    name: Build on Windows without snyk scan

    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build -PsnykScan=false

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html